
<?php
$attributes = $widget->getAttributes();
?>

<div class="row-fluid w1000 hp80">

<form id="widgetForm" class="jqform" method="post" action="/page/widget/set/p/<?=$widget->getParent()->getId()?>?token=<?=$widget->getToken()?>" data-widget="<?=$widget->getId()?>">
<input type="hidden" name="id" value="<?=$widget->getId()?>" />

<ul class="nav nav-tabs" id="article-tab">
<li><a href="#widget-content" data-toggle="tab"><?=$this->translate('Content'); ?></a></li>
		<li><a href="#widget-meta" data-toggle="tab"><?=$this->translate('Settings'); ?></a></li>
		<li><a href="#widget-geo" data-toggle="tab"><?=$this->translate('GEO-Coords'); ?></a></li>
	</ul>

	<div class="tab-content margin-bottom-10 hp80">

		<div class="tab-pane" id="widget-content">
		<?php include 'tab/widget-content.phtml'; ?>
		</div>
		<div class="tab-pane" id="widget-meta">
		<?php include 'tab/widget-meta.phtml'; ?>
		</div>
		<div class="tab-pane" id="widget-geo">
		<?php include 'tab/widget-geo.phtml'; ?>
		</div>

	</div>

	<div class="clearfix"><!--  --></div>

	<button class="btn btn-primary pull-right margin-right-8" data-type="submit"><?=$this->translate('Save'); ?></button>


	</form>

</div>

<script>

(function() {

	$form = $('#widgetForm');

	$.fn.eventManager.notify('mc.jqform', {'selector':'#widgetForm'})
	$('#submitBtn').on("click", function(e){
		e.preventDefault();
		$(this).closest('form').submit();
		return false;
	});

	$('a[data-toggle="tab"]').on('shown.bs.tab', function() {
		$('.tab-pane.active input:first ').select();
	});
	$('a[data-toggle="tab"]:first').trigger('click');
	$('.tab-pane.active input:first ').select();
	$form.find('[data-toggle="popover"]').popover({html:true});
	$form.find('.whtml').wysihtml5({'font-styles':true,'html':true});

})();

</script>
