
<div class="row-fluid box4content">

	<div class="col-md-3 text-center">
		<div class="panel circle">
			<div class="front" style="background-image:url('/images/gallery/large/img35.jpg');background-size: auto 357px;">
				<div class="box">
					<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam</p>
				</div>
			</div>
			<div class="back">
				<div class="box">
					<p>Back Side / Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam</p>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 text-center">
		<div class="panel">
			<div class="front">
				<div class="box">
					<p>Front Side</p>
				</div>
			</div>
			<div class="back" style="background-image:url('/images/gallery/large/img35.jpg');background-size: auto 357px;">
				<div class="box">
					<p>Back Side</p>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 text-center">
		<div class="panel">
			<div class="front">
				<div class="box">
					<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam</p>
				</div>
			</div>
			<div class="back">
				<div class="box">
					<p>Back Side</p>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 text-center">
		<div class="panel">
			<div class="front">
				<div class="box">
					<p>Front Side</p>
				</div>
			</div>
			<div class="back">
				<div class="box">
					<p><b>Back Side</b> / Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam</p>
				</div>
			</div>
		</div>
	</div>

</div>


<script>

$(document).ready(function(){
	$('.panel').hover(function(){
		$(this).addClass('flip');
	},function(){
		$(this).removeClass('flip');
	});
});

</script>
