
<?php
$headline = isset($attributes['headline'][$this->lang])
			? $attributes['headline'][$this->lang]
			: null;
$subline = isset($attributes['subline'][$this->lang])
			? $attributes['subline'][$this->lang]
			: null;
$intro = isset($attributes['intro'][$this->lang])
		? $attributes['intro'][$this->lang]
		: null;
$body = isset($attributes['body'][$this->lang])
		? $attributes['body'][$this->lang]
		: null;
?>
<div class="form-group">
	<label class="block"><?=$this->translate('Headline')?>:
		<input class="form-control" type="text" name="headline" value="<?=$headline?>" placeholder="" /></label>
</div>

<div class="form-group">
	<label class="block"><?=$this->translate('Subline')?>:
		<input class="form-control" type="text" name="subline" value="<?=$subline?>" placeholder="" /></label>
</div>

<div class="form-group">
	<label class="block"><?=$this->translate('Intro')?>:
		<textarea class="form-control h150 whtml" type="text" name="intro" placeholder=""><?=$intro?></textarea></label>
</div>

<div class="form-group">
	<label class="block"><?=$this->translate('Body')?>:
		<textarea class="form-control h200 whtml" type="text" name="body" placeholder=""><?=$body?></textarea></label>
</div>
