
<div class="container-fluid padding-0 h800 w1000" style="overflow:hidden;">

	<div class="row-fluid hp100">

		<div class="col-md-4 h800 padding-0 ohidden">

			<?=$this->partial('partials/editor/searchfield', array('target'=>'document'))?>

			<div id="document-tree" class="shadow-inset psb wp100 hp100">
				<ul id="holder_0" class="holder" style="display: none;"></ul>
			</div>

		</div>


		<div class="col-md-8 h800 padding-right-0 psb">

			<div id="document-form" class="hp100"></div>

			<div class="clearfix"><!--  --></div>

		</div>


	</div>

</div>

<script type="text/html" id="tmpl_treeinlay">
<% for(var i=0; i < entries.length; i++ ){ %>
<li id="<%=entries[i].id%>" class="dragdrop">
	<div class="btn-group wp100">

		<button class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
		<a id="btn_<%=entries[i].id%>" class="btn btn-xs<%=(entries[i].visible==0?' btn-warning':' btn-success')%> name structname" href="/page/document/set/id/<%=entries[i].id%>" data-target="#document-form" data-id="<%=entries[i].id%>" data-token="<%=entries[i].token%>"><%=entries[i].structname.de%></a>

		<ul class="dropdown-menu" role="menu">
			<li><a class="siteAction" href="#" data-action="load" data-id="<%=entries[i].id%>">Unterseiten</a></li>
			<li class="divider"><!-- --></li>
			<li><a class="siteAction" href="#" data-action="create" data-id="<%=entries[i].id%>">Unterseite anlegen</a></li>
			<li><a class="siteAction" href="#" data-action="visible" data-id="<%=entries[i].id%>">Diese Seite online/offline</a></li>
			<li><a class="siteAction" href="#" data-action="remove" data-id="<%=entries[i].id%>">Diese Seite löschen</a></li>
		</ul>
	</div>
	<ul id="holder_<%=entries[i].id%>" class="holder" style="display:none"></ul>
</li>
<% } %>
</script>
<script>

LangSwitch = (function(){

	defaults = {};

	function init(options) {
		defaults = $.extend(defaults, options || {});
		if(defaults.handler != undefined)
			defaults.uri = defaults.handler.attr('href') + '?token=' + defaults.handler.data('token') + '&lang=';

		prepare();
	}

	function prepare() {
		$('input.check_lang').on("change", function(e) {
			$lang = $(this).val();
			defaults.uri += $lang;
			Tree.loadForm(defaults.uri, defaults.handler);
		});
	}

	return {
		'init': init
	}
})();


Tree = (function(){

	var defaults = {'lang':'<?=$lang?>'};

	function init( options ) {
		defaults = $.extend(defaults, options || {});
	}

	function loadTree(id) {

		var _selector = '#holder_'+ id;
		$.get('/page/ajax/dtree/id/'+id, {}, function(_response) {

			$(_selector).append(tmpl('tmpl_treeinlay', {'entries':_response.documents,'_selector':_selector}));

			$(_selector + " a.structname").on("click", function(e){
				e.preventDefault();
				loadForm($(this).attr('href')+'?token='+$(this).attr('data-token'), $(this));
			});
			$.fn.eventManager.notify('mc.scroll', {selector:'#document-tree'});
			$(_selector + " a.siteAction").on("click", function(e){
				e.preventDefault();
				switch($(this).attr('data-action')) {
					case 'load':
						$holder = $('#holder_'+$(this).attr('data-id'));
						if($holder.has('li').length>0) $holder.slideToggle();
						else loadTree($(this).attr('data-id'));
						break;
					case 'remove':
						if(!confirm("wirlich löschen?")) return;
						var self=this;
						$.get('/page/document/remove/id/'+$(this).attr('data-id'), {}, function(data){
							if(data.visible == 0) {
								$('#btn_'+data._id.$id).removeClass('btn-success').addClass('btn-warning');
							}
							else if(data.visible == 1) {
								$('#btn_'+data._id.$id).removeClass('btn-warning').addClass('btn-success');
							}
							$('#'+$(self).attr('data-id')).remove();
						}, 'json');
						break;
					case 'create':
						$dataId=$(this).attr('data-id');
						$.get('/page/document/set/id/'+$dataId, {'create':true}, function(data){
							loadTree($dataId);
						}, 'json');
						$('#holder_'+$(this).attr('data-id')).empty().hide();
						break;
					case 'visible':
						$.get('/page/document/visible/id/'+$(this).attr('data-id'), {}, function(data){
							if(data.document.visible == 0) {
								$('#btn_'+data.document.id).removeClass('btn-success').addClass('btn-warning');
							}
							else if(data.document.visible == 1) {
								$('#btn_'+data.document.id).removeClass('btn-warning').addClass('btn-success');
							}
						}, 'json');
						break;
					default:
						break;
				}
			});
			$(_selector).slideToggle('slow', function(){
				if(_selector == '#holder_0') $(_selector + ' a.siteAction:first, ' + _selector + ' a.structname:first').trigger('click');
			});
		}, 'json');

	}

	function loadForm(_uri, o) {
		$(o.data('target')).empty().append($spinner);
		$.get(_uri, {}, function(data){
			$(o.data('target')).empty().append(data);
			LangSwitch.init({'handler':o});
		});
	}

	return {
		'init': init,
		'loadTree': loadTree,
		'loadForm': loadForm
	};
})();
Tree.init();
Tree.loadTree(0);

(function(){
	MC.EventManager.notify('mc.scroll', {'selector':'.tab-content'});
})();

</script>
