
<div class="container-fluid padding-0 h800 w1000" style="overflow:hidden;">

	<div class="row-fluid h800">
		<div class="col-md-4 h800 padding-0 ohidden">

			<?=$this->partial('partials/editor/searchfield', array('target'=>'user'))?>

			<div id="user-tree" class="shadow-inset padding-0 h800 psb w331">
				<ul id="holder_0" class="holder" style="display: none;"></ul>
			</div>

		</div>


		<div class="col-md-8 padding-right-0 h800">

			<div id="user-form" class=" h800"></div>

		</div>
	</div>

</div>

<script type="text/html" id="tmpl_utreeinlay">
<% for(var i=0; i < entries.length; i++ ){ %>
<li id="<%=entries[i].id%>" class="dragdrop">
	<div class="btn-group wp100">

		<button class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
		<a id="btn_<%=entries[i].id%>" class="btn btn-xs<%=(entries[i].visible==0?' btn-warning':' btn-success')%> name structname" href="/page/user/set?token=<%=entries[i].token%>" data-token="<%=entries[i].token%>" data-id="<%=entries[i].id%>" data-target="#user-form"><%=entries[i].nickname%></a>

		<ul class="dropdown-menu" role="menu">
			<li><a class="siteAction" href="#" data-action="load" data-id="<%=entries[i].id%>">Mitarbeiter</a></li>
			<li><a class="siteAction" href="#" data-action="create" data-id="<%=entries[i].id%>">Mitarbeiter anlegen</a></li>
			<li><a class="siteAction" href="#" data-action="visible" data-id="<%=entries[i].id%>">Dieser Benutzer online/offline</a></li>
			<li><a class="siteAction" href="#" data-action="remove" data-id="<%=entries[i].id%>">Diesen Benutzer löschen</a></li>
		</ul>
	</div>
	<ul id="holder_<%=entries[i].id%>" class="holder" style="display:none"></ul>
</li>
<% } %>
</script>
<script>

Tree = (function(){

	var defaults = {'lang':'<?=$this->lang?>'};

	function init( options ) {
		defaults = $.extend(defaults, options || {});
	}

	function loadTree(id) {

		var _selector = '#holder_'+ id;
		$.get('/page/ajax/user-tree/'+id, {'id':id}, function(_response){
			$(_selector).append(tmpl('tmpl_utreeinlay', {'entries':_response.users,'_selector':_selector}));
			if(id==0) $('a.structname:first').trigger('click');

			$(_selector + " a.structname").on("click", function(e){
				e.preventDefault();
				loadForm($(this).attr('href'), $(this));
			});
			$(_selector + " a.siteAction").on("click", function(e){
				e.preventDefault();
				switch($(this).attr('data-action')) {
					case 'load':
						$holder = $('#holder_'+$(this).attr('data-id'));
						if($holder.has('li').length>0) $holder.slideToggle();
						else loadTree($(this).attr('data-id'));
						$(_selector + " a.structname:first").trigger('click');
						break;
					case 'remove':
						if(!confirm("wirlich löschen?")) return;
						var self=this;
						$.get('/page/user/remove/'+$(this).attr('data-id'), {'id':$(this).attr('data-id')}, function(data){
							if(data.user.visible == 0) {
								$('#btn_'+data.user.id).removeClass('btn-success').addClass('btn-warning');
							}
							else if(data.user.visible == 1) {
								$('#btn_'+data.user.id).removeClass('btn-warning').addClass('btn-success');
							}
							$('#'+$(self).attr('data-id')).remove();
						}, 'json');
						break;
					case 'create':
						$.get('/page/user/set/'+$(this).attr('data-id'), {'token':$(this).data('token')}, function(data){
							loadTree($(this).attr('data-id'));
						}, 'json');
						$('#holder_'+$(this).attr('data-id')).empty().hide();
						break;
					case 'visible':
						$.get('/page/user/visible/id/'+$(this).attr('data-id'), {'token':$(this).attr('data-token')}, function(data) {
							if(data.user.visible == 0) {
								$('#btn_'+data.user.id).removeClass('btn-success').addClass('btn-warning');
							}
							else if(data.user.visible == 1) {
								$('#btn_'+data.user.id).removeClass('btn-warning').addClass('btn-success');
							}
							delete data.user;
							console.log(data);
							$.fn.eventManager.notify('jsonresponse', data);
						}, 'json');
						break;
					default:
						break;
				}
			});

			$(_selector).slideToggle('slow', function(){
				if(_selector == '#holder_0') $(_selector + ' a.siteAction:first, ' + _selector + ' button.structname:first').trigger('click');
			});
		}, 'json');

	}

	function loadForm(_uri, o) {
		$(o.data('target')).empty().append($spinner);
		$.get(_uri, {}, function(data){
			$(o.data('target')).empty().append(data);
		});
	}

	return {
		'init': init,
		'loadTree': loadTree,
		'loadForm': loadForm
	};
})();
Tree.init();
Tree.loadTree(0);

</script>
