<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ModelClientModelHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['distance'])) {
            $value = $data['distance'];
            $return = (string) $value;
            $this->class->reflFields['distance']->setValue($document, $return);
            $hydratedData['distance'] = $return;
        }

        /** @EmbedOne */
        if (isset($data['coordinates'])) {
            $embeddedDocument = $data['coordinates'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['coordinates'], $embeddedDocument);
            $embeddedMetadata = $this->dm->getClassMetadata($className);
            $return = $embeddedMetadata->newInstance();

            $embeddedData = $this->dm->getHydratorFactory()->hydrate($return, $embeddedDocument, $hints);
            $embeddedId = $embeddedMetadata->identifier && isset($embeddedData[$embeddedMetadata->identifier]) ? $embeddedData[$embeddedMetadata->identifier] : null;

            $this->unitOfWork->registerManaged($return, $embeddedId, $embeddedData);
            $this->unitOfWork->setParentAssociation($return, $this->class->fieldMappings['coordinates'], $document, 'coordinates');

            $this->class->reflFields['coordinates']->setValue($document, $return);
            $hydratedData['coordinates'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['datecreate'])) {
            $value = $data['datecreate'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['datecreate']->setValue($document, clone $return);
            $hydratedData['datecreate'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['firm'])) {
            $value = $data['firm'];
            $return = (string) $value;
            $this->class->reflFields['firm']->setValue($document, $return);
            $hydratedData['firm'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['zipcode'])) {
            $value = $data['zipcode'];
            $return = (string) $value;
            $this->class->reflFields['zipcode']->setValue($document, $return);
            $hydratedData['zipcode'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['streetnr'])) {
            $value = $data['streetnr'];
            $return = (string) $value;
            $this->class->reflFields['streetnr']->setValue($document, $return);
            $hydratedData['streetnr'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['city'])) {
            $value = $data['city'];
            $return = (string) $value;
            $this->class->reflFields['city']->setValue($document, $return);
            $hydratedData['city'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['phone'])) {
            $value = $data['phone'];
            $return = (string) $value;
            $this->class->reflFields['phone']->setValue($document, $return);
            $hydratedData['phone'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['fax'])) {
            $value = $data['fax'];
            $return = (string) $value;
            $this->class->reflFields['fax']->setValue($document, $return);
            $hydratedData['fax'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['mail'])) {
            $value = $data['mail'];
            $return = (string) $value;
            $this->class->reflFields['mail']->setValue($document, $return);
            $hydratedData['mail'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['token'])) {
            $value = $data['token'];
            $return = (string) $value;
            $this->class->reflFields['token']->setValue($document, $return);
            $hydratedData['token'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['shortname'])) {
            $value = $data['shortname'];
            $return = (string) $value;
            $this->class->reflFields['shortname']->setValue($document, $return);
            $hydratedData['shortname'] = $return;
        }
        return $hydratedData;
    }
}