<?php

namespace Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ClientModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientModelRepository extends DocumentRepository
{
}