<?php

namespace Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DocumentModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentModelRepository extends DocumentRepository
{
}