<?php

namespace Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserModelRepository extends DocumentRepository
{
}