<?php

namespace Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * WidgetModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetModelRepository extends DocumentRepository
{
}