<?php

namespace DoctrineMongoODMModule\Proxy\__CG__\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Image extends \Model\Image implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('distance' => NULL, 'name' => NULL, 'file' => NULL, 'uploadDate' => NULL, 'attributes' => NULL, 'length' => NULL, 'chunkSize' => NULL, 'md5' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->distance, $this->name, $this->file, $this->uploadDate, $this->attributes, $this->length, $this->chunkSize, $this->md5);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'distance', 'name', 'file', 'uploadDate', 'attributes', 'length', 'chunkSize', 'md5', 'owner', 'folder', 'isbackground', 'randompoint', 'coordinates', 'token');
        }

        return array('__isInitialized__', 'id', 'owner', 'folder', 'isbackground', 'randompoint', 'coordinates', 'token');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Image $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->distance, $this->name, $this->file, $this->uploadDate, $this->attributes, $this->length, $this->chunkSize, $this->md5);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function findGeoCoords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findGeoCoords', array());

        return parent::findGeoCoords();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setUploadDate($uploadDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUploadDate', array($uploadDate));

        return parent::setUploadDate($uploadDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDate', array());

        return parent::getUploadDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributes(\Model\ImageAttributes $attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributes', array($attributes));

        return parent::setAttributes($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributes', array());

        return parent::getAttributes();
    }

    /**
     * {@inheritDoc}
     */
    public function setLength($length)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLength', array($length));

        return parent::setLength($length);
    }

    /**
     * {@inheritDoc}
     */
    public function getLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLength', array());

        return parent::getLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setChunkSize($chunkSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChunkSize', array($chunkSize));

        return parent::setChunkSize($chunkSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getChunkSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChunkSize', array());

        return parent::getChunkSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setMd5($md5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMd5', array($md5));

        return parent::setMd5($md5);
    }

    /**
     * {@inheritDoc}
     */
    public function getMd5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMd5', array());

        return parent::getMd5();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\Model\UserModel $owner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', array($owner));

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', array());

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setFolder($folder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFolder', array($folder));

        return parent::setFolder($folder);
    }

    /**
     * {@inheritDoc}
     */
    public function getFolder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolder', array());

        return parent::getFolder();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsbackground($isbackground)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsbackground', array($isbackground));

        return parent::setIsbackground($isbackground);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsbackground()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsbackground', array());

        return parent::getIsbackground();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistance($distance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistance', array($distance));

        return parent::setDistance($distance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistance', array());

        return parent::getDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setRandompoint($randompoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRandompoint', array($randompoint));

        return parent::setRandompoint($randompoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getRandompoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRandompoint', array());

        return parent::getRandompoint();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoordinates(\Model\Coordinates $coordinates)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoordinates', array($coordinates));

        return parent::setCoordinates($coordinates);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoordinates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoordinates', array());

        return parent::getCoordinates();
    }

}
