
<div class="row-fluid">
	<form id="shortLoginForm" class="form-horizontal jqform" method="post" action="/login" >
		<div class="form-group">
			<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" id="inputEmail3" name="login" placeholder="<?=$this->translate('Email or Nickname')?>">
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
			<div class="col-sm-10">
				<input type="password" class="form-control" id="inputPassword3" name="password" placeholder="<?=$this->translate('Password')?>">
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<div class="checkbox">
					<label><input type="checkbox" name="remember"> Remember me</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-default">Sign in</button>
			</div>
		</div>
	</form>
</div>

<script>

(function(){

	$.fn.eventManager.notify('mc.jqform', {'selector':'#shortLoginForm'});

})();

</script>